enableGlobalCache: true

packageExtensions:
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
      "@sapphire/framework": "*"
      discord.js: "^13.9.1"
  "@sapphire/framework@*":
    dependencies:
      "@discordjs/builders": "*"
      discord.js: "^13.9.1"
      "discord-api-types": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
