enableGlobalCache: true

packageExtensions:
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
      "@sapphire/framework": "*"
      discord.js: "*"
  "@sapphire/discord.js-utilities@*":
    dependencies:
      discord-api-types: "*"
      discord.js: "*"
  "@sapphire/framework@*":
    dependencies:
      discord.js: "*"
  "@sapphire/plugin-logger@*":
    dependencies:
      "@sapphire/framework": "*"
      discord.js: "*"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
