enableGlobalCache: true

packageExtensions:
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
      "@sapphire/framework": "*"
      discord.js: "*"
  "@sapphire/discord.js-utilities@*":
    dependencies:
      discord-api-types: "*"
      discord.js: "*"
  "@sapphire/framework@*":
    dependencies:
      "@discordjs/builders": "*"
      discord.js: "*"
  "@sapphire/plugin-logger@*":
    dependencies:
      "@sapphire/framework": "*"
      discord.js: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
