name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    uses: bitomic/utilities/.github/workflows/node.js.yml@b28866532a9825ee01e7803aa16d51c57d4d373d
